/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/inbox/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiInboxByAddress"];
        put?: never;
        post?: never;
        delete: operations["deleteApiInboxByAddress"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiEmailById"];
        put?: never;
        post?: never;
        delete: operations["deleteApiEmailById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiInboxByAddress: {
        parameters: {
            query?: {
                page?: string;
                limit?: string;
            };
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        emails: {
                            id: string;
                            to: string;
                            from: string;
                            subject: string;
                            text: string;
                            html: string;
                            headers: {
                                [key: string]: string;
                            };
                            receivedAt: string;
                        }[];
                        pagination: {
                            page: number;
                            limit: number;
                            totalEmails: number;
                            totalPages: number;
                            hasMore: boolean;
                        };
                    };
                    "multipart/form-data": {
                        emails: {
                            id: string;
                            to: string;
                            from: string;
                            subject: string;
                            text: string;
                            html: string;
                            headers: {
                                [key: string]: string;
                            };
                            receivedAt: string;
                        }[];
                        pagination: {
                            page: number;
                            limit: number;
                            totalEmails: number;
                            totalPages: number;
                            hasMore: boolean;
                        };
                    };
                    "text/plain": {
                        emails: {
                            id: string;
                            to: string;
                            from: string;
                            subject: string;
                            text: string;
                            html: string;
                            headers: {
                                [key: string]: string;
                            };
                            receivedAt: string;
                        }[];
                        pagination: {
                            page: number;
                            limit: number;
                            totalEmails: number;
                            totalPages: number;
                            hasMore: boolean;
                        };
                    };
                };
            };
        };
    };
    deleteApiInboxByAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted: number;
                    };
                    "multipart/form-data": {
                        deleted: number;
                    };
                    "text/plain": {
                        deleted: number;
                    };
                };
            };
        };
    };
    getApiEmailById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        to: string;
                        from: string;
                        subject: string;
                        text: string;
                        html: string;
                        headers: {
                            [key: string]: string;
                        };
                        receivedAt: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        to: string;
                        from: string;
                        subject: string;
                        text: string;
                        html: string;
                        headers: {
                            [key: string]: string;
                        };
                        receivedAt: string;
                    };
                    "text/plain": {
                        id: string;
                        to: string;
                        from: string;
                        subject: string;
                        text: string;
                        html: string;
                        headers: {
                            [key: string]: string;
                        };
                        receivedAt: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                    "multipart/form-data": {
                        error: string;
                    };
                    "text/plain": {
                        error: string;
                    };
                };
            };
        };
    };
    deleteApiEmailById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted: boolean;
                    };
                    "multipart/form-data": {
                        deleted: boolean;
                    };
                    "text/plain": {
                        deleted: boolean;
                    };
                };
            };
        };
    };
    getApiHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        smtp: boolean;
                        redis: boolean;
                        uptime: number;
                    };
                    "multipart/form-data": {
                        status: string;
                        smtp: boolean;
                        redis: boolean;
                        uptime: number;
                    };
                    "text/plain": {
                        status: string;
                        smtp: boolean;
                        redis: boolean;
                        uptime: number;
                    };
                };
            };
        };
    };
}
